Cross compiles project to Scala 3
lightbend/scala-logging pull request #227
Opened 2020-08-22 03:05 UTC by amumurst

This PR contains a full reimplementation of all macros for Dotty. 

This is the first time I write any macros at all for scala, so its ***highly*** likely that they are somewhere on the scale from `completely wrong` to `somewhat okay` 😄  

Else there are some slight changes to the test classes to get Dotty running. 

The "API" of the loggers is the same, but I have absolutely no clue if things are breaking or not 😅

2020-12-20 22:00 UTC, sullis requested changes
let's upgrade to 3.0.0-M3

2020-12-20 22:00 UTC, sullis commented on project/plugins.sbt
> +addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.4.1")
please upgrade to sbt-dotty 0.5.1

2020-12-20 22:00 UTC, sullis commented on project/Dependencies.scala
> +  val dotty     = "0.26.0-RC1"
upgrade to 3.0.0-M3

2020-12-20 22:00 UTC, sullis commented on .travis.yml
> +   - 0.26.0-RC1
upgrade to 3.0.0-M3

2021-02-03 20:54 UTC, SethTisue commented
Hi. I have merge rights in this repo now, and I'll be happy to merge this and pull publishing levers if it is updated for Scala 3.0.0-M3.

2021-02-09 20:26 UTC, SethTisue commented
See #225 for discussion about the possible future of this repository.

2021-02-17 17:29 UTC, SethTisue commented
(needs rebase)

2021-02-17 17:31 UTC, SethTisue commented
Oh, and Scala 3.0.0-RC1 just hit Maven Central yesterday!

2021-02-17 17:37 UTC, amumurst commented
Yeah! It compiles for RC1 but scalatest stuff is not out yet, probably can wait for those. Working on rebase atm.

2021-02-17 17:41 UTC, SethTisue commented
@amumurst (I think it would be fine to land this for M3, then separately land an RC1 upgrade)

2021-02-17 17:41 UTC, SethTisue commented
I've requested that the ScalaTest folks publish for RC1: https://github.com/scalatest/scalatest/issues/1138#issuecomment-780718244

2021-02-18 09:24 UTC, amumurst commented
@bbonanno I had to kinda revert back to `scalatestplus-mockito` from `mockito-scala` since from what I kan see it is not doing anything about scala 3 so far (https://github.com/mockito/mockito-scala/pull/330.)

Syntax-wise its just replacing imports and `*` to `any`, but I understood from https://github.com/lightbend/scala-logging/pull/255 that the scala version is safer to use.

2021-02-18 09:42 UTC, bbonanno commented
@amumurst sadly I'm blocked by a ton of dependencies to progress to support Scala 3, in the same way you were by mockito-scala, so I totally feel your pain.
Yes, it's safer, but I guess the project can do without it until I can add Scala 3 support.

The PR had also changes to tests that were broken regardless of the mockito flavour, so I guess you wanna keep those changes

2021-02-18 10:00 UTC, amumurst commented
@bbonanno Totally! 
All changes you did are kept and working, only this https://github.com/lightbend/scala-logging/pull/227/files#diff-33835318a9975954275bb9500a41c274042970ee83606cf05c2e41a8c6bc6616R31 had to be changed in the actual test implementations 👍

2021-02-18 14:58 UTC, SethTisue approved these changes
build changes LGTM. (I'm unable to review the code changes.)

2021-02-18 15:31 UTC, amumurst commented
I do not think I have much more to add. Tests are green so it can't be that bad, no? 🤣 I guess @sullis ?

I think if anyone who actually knows these macros should stumble upon this i think these two methods are where there probably are better ways.


https://github.com/lightbend/scala-logging/pull/227/files#diff-0e17135facf79fb676040c8f9c4194ec443f5f2ffe81bc91f7655269fed1f9adR230

replacing
https://github.com/lightbend/scala-logging/blob/0057744a001c5757f5f6976c37ea6743ceace2d8/src/main/scala-2.x/com/typesafe/scalalogging/LoggerMacro.scala#L261

and

https://github.com/lightbend/scala-logging/pull/227/files#diff-0e17135facf79fb676040c8f9c4194ec443f5f2ffe81bc91f7655269fed1f9adR264

replacing
https://github.com/lightbend/scala-logging/blob/0057744a001c5757f5f6976c37ea6743ceace2d8/src/main/scala-2.x/com/typesafe/scalalogging/LoggerMacro.scala#L295

2021-02-18 15:32 UTC, SethTisue commented
I'm happy to merge regardless, if it comes to that, but let's let it sit until next week to see if any reviewers appear.

2021-02-18 17:02 UTC, sullis commented on project/Dependencies.scala
> +  val scalaTest = "3.2.4-M1"
ScalaTest 3.2.4 is available in Maven Central
https://repo1.maven.org/maven2/org/scalatest/scalatest_3.0.0-RC1/3.2.4/

2021-02-18 17:03 UTC, sullis commented on .travis.yml
> +  - 3.0.0-M3
perhaps this should be 3.0.0-RC1

2021-02-22 14:21 UTC, merged

2021-02-22 14:21 UTC, SethTisue commented
👏